name: Trigger auto deployment for goodmorningbreadsticks

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/goodmorningbreadsticks-AutoDeployTrigger-58806f23-1292-4b99-84b4-f698590b8b55.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.GOODMORNINGBREADSTICKS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.GOODMORNINGBREADSTICKS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.GOODMORNINGBREADSTICKS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}current-projects/Docker/goodmorningbreadsticks.com
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: developmentacr22626-aga0bkbhhyexh3h4.azurecr.io
          registryUsername: ${{ secrets.GOODMORNINGBREADSTICKS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.GOODMORNINGBREADSTICKS_REGISTRY_PASSWORD }}
          containerAppName: goodmorningbreadsticks
          resourceGroup: DevelopmentResourceGroup
          imageToBuild: developmentacr22626-aga0bkbhhyexh3h4.azurecr.io/goodmorningbreadsticks:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


